"""Preview and apply a release version across every file that carries it.

The locations are discovered, not listed from memory: the script searches the
tracked tree for the current version and refuses to continue when it finds one
it does not recognise. A new place that starts carrying the version therefore
surfaces here instead of being missed, and the maintainer guide can be checked
against what this reports.
"""

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
# Edited by this script.
UPDATED = (
    "pyproject.toml",
    "plugins/tao-dev/.claude-plugin/plugin.json",
    "plugins/tao-dev/.codex-plugin/plugin.json",
    "plugins/tao-dev/skills/tao-dev/scripts/taolib/__init__.py",
)
# Rewritten by their own generators once the sources above change.
GENERATED = {
    "plugins/tao-dev/skills/tao-dev/scripts/runtime.json": "scripts/export_dependencies.py",
    "uv.lock": "uv lock",
}
# Historical acceptance records: a past result keeps the version it reported.
RECORDS = ("docs/plans/",)


def current_version():
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]


def next_minor(version):
    parts = version.split(".")
    if len(parts) != 3 or not all(part.isdigit() for part in parts):
        raise SystemExit(f"Cannot derive the next minor release from {version!r}; pass one explicitly.")
    return f"{parts[0]}.{int(parts[1]) + 1}.0"


def occurrences(version):
    found = subprocess.run(["git", "-C", str(ROOT), "grep", "-n", "-F", version],
                           capture_output=True, text=True, encoding="utf-8")
    if found.returncode not in (0, 1):
        raise SystemExit(found.stderr.strip() or "git grep failed")
    rows = []
    for line in found.stdout.splitlines():
        path, number, text = line.split(":", 2)
        rows.append((path, int(number), text))
    return rows


def classify(rows):
    groups = {"updated": [], "generated": [], "records": [], "unexpected": []}
    for row in rows:
        path = row[0]
        if path in UPDATED:
            groups["updated"].append(row)
        elif path in GENERATED:
            groups["generated"].append(row)
        elif any(path.startswith(prefix) for prefix in RECORDS):
            groups["records"].append(row)
        else:
            groups["unexpected"].append(row)
    return groups


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", nargs="?", help="target version; defaults to the next minor")
    parser.add_argument("--dry-run", action="store_true", help="report the change without writing it")
    args = parser.parse_args()

    current = current_version()
    target = args.version or next_minor(current)
    if not re.fullmatch(r"\d+\.\d+\.\d+([-.][0-9A-Za-z.]+)?", target):
        raise SystemExit(f"Refusing an unrecognised version string: {target!r}")
    if target == current:
        raise SystemExit(f"The project already declares {current}.")

    groups = classify(occurrences(current))
    print(f"{current} -> {target}\n")

    for path, number, text in groups["updated"]:
        print(f"  {path}:{number}")
        print(f"    - {text.strip()}")
        print(f"    + {text.strip().replace(current, target)}")
    missing = [path for path in UPDATED if not any(row[0] == path for row in groups["updated"])]
    for path in missing:
        print(f"  {path}: does not carry {current}; check it by hand")
    for path, number, _ in groups["generated"]:
        print(f"  {path}:{number} regenerated by {GENERATED[path]}")
    for path, number, _ in groups["records"]:
        print(f"  {path}:{number} left as the historical record it is")

    if groups["unexpected"]:
        print("\nUnrecognised locations carry this version:")
        for path, number, text in groups["unexpected"]:
            print(f"  {path}:{number}: {text.strip()}")
        print("\nDecide whether each one should follow the release, then update both\n"
              "this script and docs/engineering/development.md before bumping.")
        return 2
    if missing:
        print("\nA declared location no longer carries the version; reconcile it first.")
        return 2

    if args.dry_run:
        print("\nReported only; nothing was written.")
        return 0

    for path, number, text in groups["updated"]:
        file = ROOT / path
        lines = file.read_text(encoding="utf-8").splitlines(keepends=True)
        assert lines[number - 1].rstrip("\r\n") == text, f"{path}:{number} changed since the preview"
        lines[number - 1] = lines[number - 1].replace(current, target)
        file.write_text("".join(lines), encoding="utf-8", newline="\n")
        print(f"wrote {path}:{number}")
    for command, reason in ((["uv", "lock", "--no-config"], "uv.lock"),
                            ([sys.executable, str(ROOT / "scripts/export_dependencies.py")], "runtime inventory")):
        print(f"regenerating {reason}")
        completed = subprocess.run(command, cwd=ROOT)
        if completed.returncode:
            return completed.returncode
    print("\nVersion written. Release still needs its acceptance, independent review\n"
          "and support-limit statement before a tag; this command creates neither.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
